# Generated by Django 5.0.1 on 2024-01-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_record_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
